plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

repositories {
    mavenLocal()
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    // Jar-in-Jar Percale

    modImplementation("io.ejekta.percale:percale-fabric:${percale_version}")
    include("io.ejekta.percale:percale-fabric:${percale_version}")

    modRuntimeOnly "com.terraformersmc:modmenu:${mod_menu_version}"
    modImplementation "net.fabricmc:fabric-language-kotlin:1.12.3+kotlin.2.0.21"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}
