plugins {
    id 'multiloader-fabric'
}

import groovy.json.JsonOutput
import groovy.json.JsonSlurper

sourceSets {
    gametest {
        java.srcDir('src/gametest/java')
        resources.srcDir('src/gametest/resources')
        compileClasspath += sourceSets.main.output + sourceSets.main.compileClasspath + sourceSets.main.runtimeClasspath + configurations.testCompileClasspath
        runtimeClasspath += output + compileClasspath + sourceSets.main.runtimeClasspath
    }
}

configurations {
    gametestCompileOnly.extendsFrom(compileOnly)
    gametestImplementation.extendsFrom(implementation)
    gametestImplementation.extendsFrom(testImplementation)
    gametestRuntimeOnly.extendsFrom(runtimeOnly)
    gametestRuntimeOnly.extendsFrom(testRuntimeOnly)
}

repositories {
    mavenLocal()
    maven {
        name = "Architectury Maven"
        url = uri("https://maven.architectury.dev/")
    }
}

dependencies {
    implementation("io.ejekta.kambrik:kambrik-fabric-${minecraft_version}:${kambrik_version}")
    implementation("io.ejekta.percale:percale-fabric-${minecraft_version}:${percale_version}")
    compileOnly("me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}")
    implementation "com.terraformersmc:modmenu:${mod_menu_version}"
}

loom {
    mods {
        "${mod_id}" {
            sourceSet sourceSets.gametest
            sourceSet sourceSets.main
        }
    }
    runs {
        gameTestServer {
            server()
            source sourceSets.gametest
            setConfigName('Fabric Game Test Server')
            ideConfigGenerated(true)
            runDir('runs/gametest')
            vmArg('-Dfabric-api.gametest=true')
            vmArg("-Dfabric-api.gametest.report-file=${file("$buildDir/reports/game_test/results.xml").absolutePath}")
        }
    }
}

tasks.named('compileGametestKotlin') {
    source(project(':common').fileTree('src/gametest/java'))
}

tasks.named('processGametestResources') {
    dependsOn(tasks.named('processResources'))
    from(project(':common').file('src/gametest/resources'))
    duplicatesStrategy = DuplicatesStrategy.WARN
    doLast {
        def mainMetadata = new JsonSlurper().parse(file("$buildDir/resources/main/fabric.mod.json")) as Map
        def entrypoints = new LinkedHashMap(mainMetadata.entrypoints as Map)
        entrypoints['fabric-gametest'] = ['io.ejekta.bountiful.test.BountifulFabricGameTest']
        def gametestMetadata = new LinkedHashMap(mainMetadata)
        gametestMetadata.entrypoints = entrypoints
        file("${destinationDir}/fabric.mod.json").text = JsonOutput.prettyPrint(JsonOutput.toJson(gametestMetadata))
    }
}

tasks.named('jar', Jar) {
    dependsOn(tasks.named('processResources'))
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    from("$buildDir/resources/main") {
        include('fabric.mod.json')
    }
}

tasks.named('runGameTestServer') {
    dependsOn(tasks.named('gametestClasses'))
}
