# Project identity
version=8.0.0-beta.1
group=io.ejekta.bountiful
mod_name=Bountiful
mod_id=bountiful
license=LGPL 3.0
credits=
description=Bountiful adds bounty boards to the world.
minecraft_version_range=[1.21, 1.21.1]

# Deps
kambrik_version=8.0.0-beta.1
percale_version=1.0.0-beta.1
cloth_config_version=15.0.140

# Gradle
org.gradle.jvmargs=-Xmx3G
