# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=8.0.0-dev.1
kambrik_version=8.0.0-dev.25
percale_version=1.0.0-dev.25

group=io.ejekta.bountiful
java_version=21

# Deps
mod_menu_version=11.0.3

# Common
minecraft_version=1.21
mod_name=Bountiful
mod_author=Ejektaflex
mod_id=bountiful
license=LGPL 3.0
credits=
description=Bountiful adds bounty boards to the world.
minecraft_version_range=[1.21, 1.21.1]
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21-20240613.152323
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.11.10


# Fabric
fabric_version=0.110.0+1.21.1
fabric_loader_version=0.16.9

# Forge
forge_version=51.0.17
forge_loader_version_range=[51,)

# NeoForge, versions at https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.0.167
neoforge_loader_version_range=[4,)

cloth_config_version=15.0.140

forgelike_adapter_version=5.6.0
forgelike_adapter_version_range=[5,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
