# Project identity
version=8.0.0-beta.1
group=io.ejekta.bountiful
mod_name=Bountiful
mod_id=bountiful
mod_author=Ejektaflex
license=LGPL 3.0
credits=
description=Bountiful adds bounty boards to the world.
minecraft_version_range=[26.1.2]

# Deps
kambrik_version=9.0.0-SNAPSHOT.1
percale_version=2.0.0-SNAPSHOT.1
cloth_config_version=15.0.140

# Gradle
org.gradle.jvmargs=-Xmx3G
