modLoader = "kotlinforforge"
loaderVersion = "${forgelike_adapter_version_range}"
#issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${description}
'''
#logoFile = ""

[[mixins]]
config = "bountiful.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type="required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kotlinforforge"
type="required"
versionRange = "${forgelike_adapter_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kambrik"
type="required"
versionRange = "${kambrik_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "percale"
type="required"
versionRange = "${percale_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type="required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
