plugins {
    id 'multiloader-neoforge'
}

repositories {
    mavenLocal()
    maven {
        name = "Architectury Maven"
        url = uri("https://maven.architectury.dev/")
    }
}

dependencies {
    implementation("io.ejekta.kambrik:kambrik-neoforge:${kambrik_version}")
    implementation("io.ejekta.percale:percale-neoforge:${percale_version}")
    implementation("me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}")
}
